const router = require('express').Router();
const User = require('../models/User');
const Couple = require('../models/Couple');
const Message = require('../models/Message');
const CanvasState = require('../models/CanvasState');
const Memory = require('../models/Memory');
const DiaryEntry = require('../models/DiaryEntry');
const CinemaState = require('../models/CinemaState');
const BucketListItem = require('../models/BucketListItem');
const authMiddleware = require('../middleware/authMiddleware');

/**
 * POST /api/couples/generate-invite
 * Generate a unique invite code for the authenticated user
 * Auth: Required
 */
router.post('/generate-invite', authMiddleware, async (req, res) => {
  try {
    const userId = req.user.id; // From JWT token

    console.log('📋 Generate invite for user:', userId);

    // Check if user already has a couple
    const existingCouple = await Couple.findOne({
      $or: [{ user1Id: userId }, { user2Id: userId }]
    });

    if (existingCouple) {
      // If already connected, cannot generate a new invite
      if (existingCouple.status === 'connected') {
        return res.status(400).json({
          msg: 'You already have a partner connection',
          code: 'COUPLE_EXISTS'
        });
      }

      // If a pending invite already exists for this user, return it
      if (existingCouple.status === 'pending' && existingCouple.user1Id.toString() === userId) {
        return res.status(200).json({
          msg: 'Existing invite code retrieved',
          inviteCode: existingCouple.inviteCode,
          coupleId: existingCouple._id,
          expiresIn: '7 days'
        });
      }

      // Fallback for any other pending state where user is already involved
      return res.status(400).json({
        msg: 'You already have a pending partner invitation',
        code: 'PENDING_COUPLE_EXISTS'
      });
    }

    // Create new couple with user1 (invite code auto-generated by schema)
    const newCouple = new Couple({
      user1Id: userId,
      status: 'pending'
    });

    await newCouple.save();

    // Update user with coupleId
    await User.findByIdAndUpdate(userId, { coupleId: newCouple._id });

    console.log('✅ Invite generated:', newCouple.inviteCode);

    res.status(201).json({
      msg: 'Invite code generated successfully',
      inviteCode: newCouple.inviteCode,
      coupleId: newCouple._id,
      expiresIn: '7 days'
    });
  } catch (error) {
    console.error('🔥 Generate invite error:', error.message);
    res.status(500).json({
      msg: 'Error generating invite code',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * POST /api/couples/accept-invite
 * Accept an invite code and connect with partner
 * Auth: Required
 * Body: { inviteCode }
 */
router.post('/accept-invite', authMiddleware, async (req, res) => {
  try {
    const { inviteCode } = req.body;
    const userId = req.user.id; // From JWT token

    console.log('🤝 Accept invite:', inviteCode, 'for user:', userId);

    if (!inviteCode) {
      return res.status(400).json({
        msg: 'Invite code is required',
        code: 'MISSING_INVITE_CODE'
      });
    }

    // Find couple by invite code
    const couple = await Couple.findOne({
      inviteCode: inviteCode.toUpperCase()
    });

    if (!couple) {
      return res.status(404).json({
        msg: 'Invalid or expired invite code',
        code: 'INVALID_CODE'
      });
    }

    if (couple.status === 'connected') {
      return res.status(400).json({
        msg: 'This invite has already been accepted',
        code: 'ALREADY_CONNECTED'
      });
    }

    if (couple.user1Id.toString() === userId) {
      return res.status(400).json({
        msg: 'You cannot accept your own invite',
        code: 'SELF_INVITE'
      });
    }

    // Check if user already has a couple
    const userCouple = await Couple.findOne({
      $or: [{ user1Id: userId }, { user2Id: userId }]
    });

    if (userCouple) {
      const isOwnPendingInvite =
        userCouple.status === 'pending' &&
        userCouple.user1Id?.toString() === userId &&
        !userCouple.user2Id;

      // If user has only their own pending invite, clean it up and allow accepting partner's code
      if (isOwnPendingInvite) {
        await User.findByIdAndUpdate(userId, { coupleId: null });
        await Couple.findByIdAndDelete(userCouple._id);
      } else {
        return res.status(400).json({
          msg: 'You already have a partner connection. Disconnect first.',
          code: 'USER_ALREADY_COUPLED'
        });
      }
    }

    // Update couple to connected
    couple.user2Id = userId;
    couple.status = 'connected';
    couple.connectedAt = new Date();
    couple.isActive = false; // Will be set to true when users go online
    couple.inviteCode = null; // Invalidate invite code after use
    await couple.save();

    // Update both users with coupleId
    await User.findByIdAndUpdate(couple.user1Id, { coupleId: couple._id });
    await User.findByIdAndUpdate(userId, { coupleId: couple._id });

    console.log('✅ Couple connected:', couple._id);

    res.status(200).json({
      msg: 'Successfully connected with partner!',
      coupleId: couple._id,
      couple: {
        _id: couple._id,
        status: couple.status,
        connectedAt: couple.connectedAt,
        isActive: couple.isActive
      }
    });
  } catch (error) {
    console.error('🔥 Accept invite error:', error.message);
    res.status(500).json({
      msg: 'Error accepting invite',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * GET /api/couples/my-couple
 * Get authenticated user's couple information
 * Auth: Required
 */
router.get('/my-couple', authMiddleware, async (req, res) => {
  try {
    const userId = req.user.id; // From JWT token

    const couple = await Couple.findOne({
      $or: [{ user1Id: userId }, { user2Id: userId }]
    })
      .populate('user1Id', 'name email initials profileColor _id')
      .populate('user2Id', 'name email initials profileColor _id');

    if (!couple) {
      return res.status(404).json({
        msg: 'No couple connection found',
        code: 'NO_COUPLE'
      });
    }

    res.json({
      msg: 'Couple info retrieved',
      couple: {
        _id: couple._id,
        user1: couple.user1Id,
        user2: couple.user2Id,
        disconnectRequestedBy: couple.disconnectRequestedBy,
        status: couple.status,
        isActive: couple.isActive,
        createdAt: couple.createdAt,
        connectedAt: couple.connectedAt
      }
    });
  } catch (error) {
    console.error('🔥 Get my couple error:', error.message);
    res.status(500).json({
      msg: 'Error fetching couple info',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * GET /api/couples/info/:coupleId
 * Get couple information by ID
 * Auth: Required (for security)
 */
router.get('/info/:coupleId', authMiddleware, async (req, res) => {
  try {
    const { coupleId } = req.params;

    const couple = await Couple.findById(coupleId)
      .populate('user1Id', 'name email initials profileColor _id')
      .populate('user2Id', 'name email initials profileColor _id');

    if (!couple) {
      return res.status(404).json({
        msg: 'Couple not found',
        code: 'COUPLE_NOT_FOUND'
      });
    }

    res.json({
      msg: 'Couple info retrieved',
      couple: {
        _id: couple._id,
        user1: couple.user1Id,
        user2: couple.user2Id,
        disconnectRequestedBy: couple.disconnectRequestedBy,
        status: couple.status,
        isActive: couple.isActive,
        createdAt: couple.createdAt,
        connectedAt: couple.connectedAt
      }
    });
  } catch (error) {
    console.error('🔥 Get couple info error:', error.message);
    res.status(500).json({
      msg: 'Error fetching couple info',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * DELETE /api/couples/disconnect
 * Disconnect from partner (break couple connection)
 * Auth: Required
 */
router.delete('/disconnect', authMiddleware, async (req, res) => {
  try {
    const userId = req.user.id;

    console.log('💔 Disconnect couple for user:', userId);

    const couple = await Couple.findOne({
      $or: [{ user1Id: userId }, { user2Id: userId }]
    });

    if (!couple) {
      return res.status(404).json({
        msg: 'No couple connection found to disconnect',
        code: 'NO_COUPLE'
      });
    }

    // Clear coupleId from both users
    await User.findByIdAndUpdate(couple.user1Id, { coupleId: null });
    await User.findByIdAndUpdate(couple.user2Id, { coupleId: null });

    // Delete the couple document
    await Couple.findByIdAndDelete(couple._id);

    console.log('✅ Couple disconnected:', couple._id);

    res.json({
      msg: 'Successfully disconnected from partner'
    });
  } catch (error) {
    console.error('🔥 Disconnect error:', error.message);
    res.status(500).json({
      msg: 'Error disconnecting from partner',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * POST /api/couples/disconnect-request
 * Mutual digital shredder flow
 * Auth: Required
 * Body (optional): { action: 'reject' }
 */
router.post('/disconnect-request', authMiddleware, async (req, res) => {
  try {
    const userId = req.user.id;
    const { action } = req.body || {};

    const couple = await Couple.findOne({
      $or: [{ user1Id: userId }, { user2Id: userId }]
    });

    if (!couple) {
      return res.status(404).json({
        msg: 'No couple connection found',
        code: 'NO_COUPLE'
      });
    }

    const requesterId = couple.disconnectRequestedBy ? couple.disconnectRequestedBy.toString() : null;

    // Optional reject action for partner-facing "Reject Request" button
    if (action === 'reject' && requesterId && requesterId !== userId) {
      couple.disconnectRequestedBy = null;
      await couple.save();

      return res.json({
        msg: 'Disconnect request cancelled.',
        disconnectRequestedBy: null
      });
    }

    // Scenario A: Initiation
    if (!requesterId) {
      couple.disconnectRequestedBy = userId;
      await couple.save();

      return res.json({
        msg: 'Disconnect request sent. Waiting for partner approval.',
        disconnectRequestedBy: couple.disconnectRequestedBy
      });
    }

    // Scenario B: Cancellation by initiator
    if (requesterId === userId) {
      couple.disconnectRequestedBy = null;
      await couple.save();

      return res.json({
        msg: 'Disconnect request cancelled.',
        disconnectRequestedBy: null
      });
    }

    // Scenario C: Mutual approval by partner => permanent shred
    const coupleId = couple._id;

    await Promise.all([
      User.updateMany(
        { _id: { $in: [couple.user1Id, couple.user2Id].filter(Boolean) } },
        { $set: { coupleId: null } }
      ),
      Message.deleteMany({ coupleId }),
      CanvasState.deleteMany({ coupleId }),
      Memory.deleteMany({ coupleId }),
      DiaryEntry.deleteMany({ coupleId }),
      CinemaState.deleteMany({ coupleId }),
      BucketListItem.deleteMany({ coupleId })
    ]);

    await Couple.findByIdAndDelete(coupleId);

    return res.json({
      msg: 'Room permanently shredded.',
      shredded: true
    });
  } catch (error) {
    console.error('🔥 Disconnect request error:', error.message);
    return res.status(500).json({
      msg: 'Error processing disconnect request',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

module.exports = router;
